Repository GamblingKings/GamblingKingsBackend, pull requests merged in 2020-08, with the labels that each got.

#18 Add game state related functions
  README.md
  __test__/dynamodb/gameDBService.test.ts
  __test__/dynamodb/gameStateDBService.test.ts
  __test__/functions/connection/onConnect.test.ts
  __test__/functions/connection/onDisconnect.test.ts
  __test__/functions/connection/onSetUsername.test.ts
  __test__/functions/lobby/onGetAllGames.test.ts
  __test__/functions/lobby/onGetAllUsers.test.ts
  __test__/functions/lobby/onJoinGame.test.ts
  __test__/functions/lobby/onLeaveGame.test.ts
  __test__/functions/lobby/onSendMessage.test.ts
  __test__/games/mahjong/Wall/HongKongWall.test.ts
  __test__/testConstants.ts
  __test__/websocket/createWSResponse.test.ts
  dynamodb.yml
  jest.config.js
  package.json
  serverless.yml
  src/dynamodb/gameDBService.ts
  src/dynamodb/gameStateDBService.ts
  src/dynamodb/userDBService.ts
  src/enums/MeldEnum.ts
  src/enums/WebSocketActionsEnum.ts
  src/enums/WindEnum.ts
  src/enums/states.ts
  src/functions/connection/onConnect.ts
  src/functions/connection/onDisconnect.ts
  src/functions/connection/onSetUsername.ts
  src/functions/functionsHelper.ts
  src/functions/game/onDrawTile.ts
  src/functions/game/onGamePageLoad.ts
  src/functions/game/onPlayTile.ts
  src/functions/game/onPlayedTileInteraction.ts
  src/functions/lobby/onCreateGame.ts
  src/functions/lobby/onGetAllGames.ts
  src/functions/lobby/onGetAllUsers.ts
  src/functions/lobby/onJoinGame.ts
  src/functions/lobby/onLeaveGame.ts
  src/functions/lobby/onSendMessage.ts
  src/functions/lobby/onStartGame.ts
  src/functions/onDisconnect.ts
  src/games/mahjong/Wall/Wall.ts
  src/models/Game.ts
  src/models/GameState.ts
  src/models/User.ts
  src/models/Version.ts
  src/types/gameUpdate.ts
  src/types/payload.ts
  src/types/response.ts
  src/utils/constants.ts
  src/websocket/broadcast/gameBroadcast.ts
  src/websocket/broadcast/gameStateBroadcast.ts
  src/websocket/broadcast/userBroadcast.ts
  src/websocket/createWSResponse.ts
  webpack.config.js
Labels: enhancement, new addition

#19 Refactor PLAYED_TILE_INTERACTION and INTERACTION_SUCCESS
  README.md
  __test__/dynamodb/gameStateDBService.test.ts
  __test__/testConstants.ts
  package.json
  src/dynamodb/gameStateDBService.ts
  src/functions/game/onGamePageLoad.ts
  src/functions/game/onPlayedTileInteraction.ts
  src/models/GameState.ts
  src/types/payload.ts
Labels: enhancement

#21 Fix bug in onPlayedTileInteraction lambda function
  package.json
  src/functions/functionsHelper.ts
  src/functions/game/onPlayedTileInteraction.ts
  src/types/payload.ts
  src/websocket/createWSResponse.ts
Labels: bug, enhancement

#22 Fix serverless offline cache issue
  .serverless_plugins/offline-invalidate/index.js
  __test__/functions/connection/onConnect.test.ts
  package.json
  serverless.yml
Labels: enhancement

#23 Modified ci slack notification
  .github/workflows/ci.yml
Labels: enhancement

#24 Fix START_GAME route
  __test__/dynamodb/gameDBService.test.ts
  package.json
  serverless.yml
  src/dynamodb/gameDBService.ts
  src/functions/lobby/onStartGame.ts
Labels: enhancement

#26 Incorporate MeldEnum.WIN in onPlayedTileInteraction lambda
  package.json
  src/functions/functionsHelper.ts
  src/functions/game/onPlayedTileInteraction.ts
  src/types/payload.ts
  yarn.lock
Labels: enhancement

#20 Add WIN_ROUND action to websocket connection
  .eslintrc.yml
  README.md
  __test__/dynamodb/dbTestHelpers.ts
  __test__/dynamodb/gameStateDBService.test.ts
  __test__/websocket/createWSResponse.test.ts
  serverless.yml
  src/dynamodb/gameStateDBService.ts
  src/enums/WebSocketActionsEnum.ts
  src/functions/game/onWinRound.ts
  src/types/payload.ts
  src/websocket/broadcast/gameBroadcast.ts
  src/websocket/createWSResponse.ts
Labels: new addition

#27 Add start-game and in-game Self Play Tile functionality and route
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  README.md
  __test__/dynamodb/gameStateDBService.test.ts
  __test__/games/mahjong/Wall/HongKongWall.test.ts
  __test__/websocket/createWSResponse.test.ts
  jest-dynalite-config.js
  package.json
  scripts/kill_db_process.sh
  serverless.yml
  src/dynamodb/dbHelper.ts
  src/dynamodb/gameStateDBService.ts
  src/enums/WebSocketActionsEnum.ts
  src/functions/game/onGamePageLoad.ts
  src/functions/game/onSelfPlayTile.ts
  src/games/mahjong/Tile/map/TileMapper.ts
  src/games/mahjong/Wall/version/HongKongWall.ts
  src/games/mahjong/types/MahjongHand.ts
  src/models/GameState.ts
  src/types/payload.ts
  src/websocket/broadcast/gameBroadcast.ts
  src/websocket/createWSResponse.ts
  yarn.lock
Labels: enhancement, new addition

#30 Added DRAW_ROUND response in onDrawTile lambda
  __test__/dynamodb/gameStateDBService.test.ts
  __test__/websocket/createWSResponse.test.ts
  src/dynamodb/gameStateDBService.ts
  src/enums/WebSocketActionsEnum.ts
  src/types/payload.ts
  src/websocket/broadcast/gameBroadcast.ts
  src/websocket/createWSResponse.ts
Labels: enhancement, new addition

#31 Fix WIN_ROUND bug
  serverless.yml
  src/enums/WebSocketActionsEnum.ts
  src/functions/game/onWinRound.ts
  src/websocket/createWSResponse.ts
Labels: bug

#32 Fixed sending GAME_START after WIN_ROUND
  __test__/utils/broadcastHelper.test.ts
  src/functions/game/onWinRound.ts
  src/games/mahjong/types/MahjongTypes.ts
  src/utils/broadcastHelper.ts
Labels: bug, enhancement

#33 Fix winning tiles in handPointResults received from client
  README.md
  package.json
  src/functions/functionsHelper.ts
  src/functions/game/onPlayedTileInteraction.ts
  src/functions/game/onWinRound.ts
  src/games/mahjong/types/MahjongTypes.ts
  src/types/payload.ts
  yarn.lock
Labels: enhancement

#34 Fix start new round functions and use it after DRAW_ROUND
  README.md
  src/dynamodb/gameStateDBService.ts
  src/functions/game/onWinRound.ts
  src/websocket/broadcast/gameBroadcast.ts
Labels: bug, enhancement

#35 Update dependencies
  package.json
  yarn.lock
Labels: enhancement
